docker:
  db: {}
domains: []
global:
  name: filestate_git
  type: app
  version: 7.6.0
wex:
  migration: 1
  version: 6.0.112
test:
  coverage:
    last_report:
      covered: 603
      excluded: 46
      missing: 597
      percent: 50.25
      total: 1200
